<h2>Sign up using this form</h2>

<?php echo $this->tag->form("login/login"); ?>

    <p>
        <label for="name">Username</label>
        <?php echo $this->tag->textField("username"); ?>
    </p>

    <p>
        <label for="email">Password</label>
        <?php echo $this->tag->passwordField("password"); ?>
    </p>

    <p>
        <?php echo $this->tag->submitButton("Register"); ?>
    </p>

</form>


